spring.application.name=simulador

mqtt.broker.url=${MQTT_BROKER_URL}
mqtt.client.id=${MQTT_CLIENT_ID:simulador-client}

server.port=8080
management.endpoints.web.exposure.include=health,info,metrics,env
management.endpoint.health.show-details=always
management.endpoint.metrics.enabled=true

spring.web.error.include-message=always
spring.web.error.include-binding-errors=always
spring.web.error.include-exception=true
spring.web.error.include-stacktrace=on_param

logging.level.pro.ms.simulador=ERROR
logging.level.org.springframework.web=ERROR